### ISSUE TITLE
CloudProxy 우회 문제

### ISSUE THREAD

**Issue by Dobob1022** [Team-IVIag/IVIag-Viewer#11]
결국 다운로드는 안되는것인가요.. CloudProxy에서 막히는듯 합니다 

====LOG===
MaruMangaParser Fail detour CloudProxy.
[2016-07-10 05:19:58][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fail
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

**Comment by HelloWorld017** [comment]
혹시 정확한 URL을 주실 수 있나요?

**Comment by Dobob1022** [comment]
새로운 로그를 드리겟습니다 명탐정 코난을 예로 들었습니다.

===LOG===
MaruVolumeParser Manga url parsing success: 명탐정 코난 20권
MaruVolumeParser Manga url parsing success: 명탐정 코난 21권
MaruVolumeParser Manga url parsing success: 명탐정 코난 22권
MaruVolumeParser Manga url parsing success: 명탐정 코난 23권
MaruVolumeParser Manga url parsing success: 명탐정 코난 24권
MaruVolumeParser Manga url parsing success: 명탐정 코난 25권
MaruVolumeParser Manga url parsing success: 명탐정 코난 26권
MaruVolumeParser Manga url parsing success: 명탐정 코난 27권
MaruVolumeParser Manga url parsing success: 명탐정 코난 28권
MaruVolumeParser Manga url parsing success: 명탐정 코난 29권
MaruVolumeParser Manga url parsing success: 명탐정 코난 30권
MaruVolumeParser Manga url parsing success: 명탐정 코난 31권
MaruVolumeParser Manga url parsing success: 명탐정 코난 32권
MaruVolumeParser Manga url parsing success: 명탐정 코난 33권
MaruVolumeParser Manga url parsing success: 명탐정 코난 34권
MaruVolumeParser Manga url parsing success: 명탐정 코난 35권
MaruVolumeParser Manga url parsing success: 명탐정 코난 36권
MaruVolumeParser Manga url parsing success: 명탐정 코난 37권
MaruVolumeParser Manga url parsing success: 명탐정 코난 38권
MaruVolumeParser Manga url parsing success: 명탐정 코난 39권
MaruVolumeParser Manga url parsing success: 명탐정 코난 40권
MaruVolumeParser Manga url parsing success: 명탐정 코난 41권
MaruVolumeParser Manga url parsing success: 명탐정 코난 42권
MaruVolumeParser Manga url parsing success: 명탐정 코난 43권
MaruVolumeParser Manga url parsing success: 명탐정 코난 44권
MaruVolumeParser Manga url parsing success: 명탐정 코난 45권
MaruVolumeParser Manga url parsing success: 명탐정 코난 46권
MaruVolumeParser Manga url parsing success: 명탐정 코난 47권
MaruVolumeParser Manga url parsing success: 명탐정 코난 48권
MaruVolumeParser Manga url parsing success: 명탐정 코난 49권
MaruVolumeParser Manga url parsing success: 명탐정 코난 50권
MaruVolumeParser Manga url parsing success: 명탐정 코난 51권
MaruVolumeParser Manga url parsing success: 명탐정 코난 52권
MaruVolumeParser Manga url parsing success: 명탐정 코난 53권
MaruVolumeParser Manga url parsing success: 명탐정 코난 54권
MaruVolumeParser Manga url parsing success: 명탐정 코난 55권
MaruVolumeParser Manga url parsing success: 명탐정 코난 56권
MaruVolumeParser Manga url parsing success: 명탐정 코난 57권
MaruVolumeParser Manga url parsing success: 명탐정 코난 58권
MaruVolumeParser Manga url parsing success: 명탐정 코난 59권
MaruVolumeParser Manga url parsing success: 명탐정 코난 60권
MaruVolumeParser Manga url parsing success: 명탐정 코난 61권
MaruVolumeParser Manga url parsing success: 명탐정 코난 62권
MaruVolumeParser Manga url parsing success: 명탐정 코난 63권
MaruVolumeParser Manga url parsing success: 명탐정 코난 64권
MaruVolumeParser Manga url parsing success: 명탐정 코난 65권
MaruVolumeParser Manga url parsing success: 명탐정 코난 66권
MaruVolumeParser Manga url parsing success: 명탐정 코난 67권
MaruVolumeParser Manga url parsing success: 명탐정 코난 68권
MaruVolumeParser Manga url parsing success: 명탐정 코난 69권
MaruVolumeParser Manga url parsing success: 명탐정 코난 70권
MaruVolumeParser Manga url parsing success: 명탐정 코난 71권
MaruVolumeParser Manga url parsing success: 명탐정 코난 72권
MaruVolumeParser Manga url parsing success: 명탐정 코난 73권
MaruVolumeParser Manga url parsing success: 명탐정 코난 74권
MaruVolumeParser Manga url parsing success: 명탐정 코난 75권
MaruVolumeParser Manga url parsing success: 명탐정 코난 76권
MaruVolumeParser Manga url parsing success: 명탐정 코난 77권
MaruVolumeParser Manga url parsing success: 명탐정 코난 78권
MaruVolumeParser Manga url parsing success: 명탐정 코난 79권
MaruVolumeParser Manga url parsing success: 명탐정 코난 80권
MaruVolumeParser Manga url parsing success: 명탐정 코난 81권
MaruVolumeParser Manga url parsing success: 명탐정 코난 82권
MaruVolumeParser Manga url parsing success: 명탐정 코난 83권
MaruVolumeParser Manga url parsing success: 명탐정 코난 84권
MaruVolumeParser Manga url parsing success: 명탐정 코난 894~900화
MaruVolumeParser Manga url parsing success: 명탐정 코난 901~905화
MaruVolumeParser Manga url parsing success: 명탐정 코난 906~910화
MaruVolumeParser Manga url parsing success: 명탐정 코난 911~915화
MaruVolumeParser Manga url parsing success: 명탐정 코난 916~920화
MaruVolumeParser Manga url parsing success: 명탐정 코난 921화
MaruVolumeParser Manga url parsing success: 명탐정 코난 922화
MaruVolumeParser Manga url parsing success: 명탐정 코난 923화
MaruVolumeParser Manga url parsing success: 명탐정 코난 924화
MaruVolumeParser Manga url parsing success: 명탐정 코난 925화
MaruVolumeParser Manga url parsing success: 명탐정 코난 926화
MaruVolumeParser Manga url parsing success: 명탐정 코난 927화
MaruVolumeParser Manga url parsing success: 명탐정 코난 928화
MaruVolumeParser Manga url parsing success: 명탐정 코난 929화
MaruVolumeParser Manga url parsing success: 명탐정 코난 930화
MaruVolumeParser Manga url parsing success: 명탐정 코난 931화
MaruVolumeParser Manga url parsing success: 명탐정 코난 932화
MaruVolumeParser Manga url parsing success: 명탐정 코난 933화
MaruVolumeParser Manga url parsing success: 명탐정 코난 934화
MaruVolumeParser Manga url parsing success: 명탐정 코난 935화
MaruVolumeParser Manga url parsing success: 명탐정 코난 936화
MaruVolumeParser Manga url parsing success: 명탐정 코난 937화
MaruVolumeParser Manga url parsing success: 명탐정 코난 938화
MaruVolumeParser Manga url parsing success: 명탐정 코난 939화
MaruVolumeParser Manga url parsing success: 명탐정 코난 940화
MaruVolumeParser Manga url parsing success: 명탐정 코난 941화
MaruVolumeParser Manga url parsing success: 명탐정 코난 942화
MaruVolumeParser Manga url parsing success: 명탐정 코난 943화
MaruVolumeParser Manga url parsing success: 명탐정 코난 944화
MaruVolumeParser Manga url parsing success: 명탐정 코난 945화
MaruVolumeParser Manga url parsing success: 명탐정 코난 946화
MaruVolumeParser Manga url parsing success: 명탐정 코난 947화
MaruVolumeParser Manga url parsing success: 명탐정 코난 948화
MaruVolumeParser Manga url parsing success: 명탐정 코난 949화
MaruVolumeParser Manga url parsing success: 명탐정 코난 950화
MaruVolumeParser Manga url parsing success: 명탐정 코난 951화
MaruVolumeParser Manga url parsing success: 명탐정 코난 952화
MaruVolumeParser Manga url parsing success: 명탐정 코난 953화
MaruVolumeParser Manga url parsing success: 명탐정 코난 954화
MaruVolumeParser Manga url parsing success: 명탐정 코난 955화
MaruVolumeParser Manga url parsing success: 명탐정 코난 956화
MaruVolumeParser Manga url parsing success: 명탐정 코난 957화
MaruVolumeParser Manga url parsing success: 명탐정 코난 958화
MaruVolumeParser Manga url parsing success: 명탐정 코난 959화
MaruVolumeParser Manga url parsing success: 명탐정 코난 960화
MaruVolumeParser Manga url parsing success: 명탐정 코난 961화
MaruVolumeParser Thumbnail parsing success: http://marumaru.in/quickimage/1cb2ce
0e43268df25a0226c10c2dbcf6.jpg
MaruVolumeParser Thumbnail parsing success: http://marumaru.in/like.png
MaruVolumeParser Find img tag. Finish find thumbnails.
MaruVolumeParser Manga url parsing success: 명탐정 코난 1권
MaruVolumeParser Manga url parsing success: 명탐정 코난 2권
MaruVolumeParser Manga url parsing success: 명탐정 코난 3권
MaruVolumeParser Manga url parsing success: 명탐정 코난 4권
MaruVolumeParser Manga url parsing success: 명탐정 코난 5권
MaruVolumeParser Manga url parsing success: 명탐정 코난 6권
MaruVolumeParser Manga url parsing success: 명탐정 코난 7권
MaruVolumeParser Manga url parsing success: 명탐정 코난 8권
MaruVolumeParser Manga url parsing success: 명탐정 코난 9권
MaruVolumeParser Manga url parsing success: 명탐정 코난 10권
MaruVolumeParser Manga url parsing success: 명탐정 코난 11권
MaruVolumeParser Manga url parsing success: 명탐정 코난 12권
MaruVolumeParser Manga url parsing success: 명탐정 코난 13권
MaruVolumeParser Manga url parsing success: 명탐정 코난 14권
MaruVolumeParser Manga url parsing success: 명탐정 코난 15권
MaruVolumeParser Manga url parsing success: 명탐정 코난 16권
MaruVolumeParser Manga url parsing success: 명탐정 코난 17권
MaruVolumeParser Manga url parsing success: 명탐정 코난 18권
MaruVolumeParser Manga url parsing success: 명탐정 코난 19권
MaruVolumeParser Manga url parsing success: 명탐정 코난 20권
MaruVolumeParser Manga url parsing success: 명탐정 코난 21권
MaruVolumeParser Manga url parsing success: 명탐정 코난 22권
MaruVolumeParser Manga url parsing success: 명탐정 코난 23권
MaruVolumeParser Manga url parsing success: 명탐정 코난 24권
MaruVolumeParser Manga url parsing success: 명탐정 코난 25권
MaruVolumeParser Manga url parsing success: 명탐정 코난 26권
MaruVolumeParser Manga url parsing success: 명탐정 코난 27권
MaruVolumeParser Manga url parsing success: 명탐정 코난 28권
MaruVolumeParser Manga url parsing success: 명탐정 코난 29권
MaruVolumeParser Manga url parsing success: 명탐정 코난 30권
MaruVolumeParser Manga url parsing success: 명탐정 코난 31권
MaruVolumeParser Manga url parsing success: 명탐정 코난 32권
MaruVolumeParser Manga url parsing success: 명탐정 코난 33권
MaruVolumeParser Manga url parsing success: 명탐정 코난 34권
MaruVolumeParser Manga url parsing success: 명탐정 코난 35권
MaruVolumeParser Manga url parsing success: 명탐정 코난 36권
MaruVolumeParser Manga url parsing success: 명탐정 코난 37권
MaruVolumeParser Manga url parsing success: 명탐정 코난 38권
MaruVolumeParser Manga url parsing success: 명탐정 코난 39권
MaruVolumeParser Manga url parsing success: 명탐정 코난 40권
MaruVolumeParser Manga url parsing success: 명탐정 코난 41권
MaruVolumeParser Manga url parsing success: 명탐정 코난 42권
MaruVolumeParser Manga url parsing success: 명탐정 코난 43권
MaruVolumeParser Manga url parsing success: 명탐정 코난 44권
MaruVolumeParser Manga url parsing success: 명탐정 코난 45권
MaruVolumeParser Manga url parsing success: 명탐정 코난 46권
MaruVolumeParser Manga url parsing success: 명탐정 코난 47권
MaruVolumeParser Manga url parsing success: 명탐정 코난 48권
MaruVolumeParser Manga url parsing success: 명탐정 코난 49권
MaruVolumeParser Manga url parsing success: 명탐정 코난 50권
MaruVolumeParser Manga url parsing success: 명탐정 코난 51권
MaruVolumeParser Manga url parsing success: 명탐정 코난 52권
MaruVolumeParser Manga url parsing success: 명탐정 코난 53권
MaruVolumeParser Manga url parsing success: 명탐정 코난 54권
MaruVolumeParser Manga url parsing success: 명탐정 코난 55권
MaruVolumeParser Manga url parsing success: 명탐정 코난 56권
MaruVolumeParser Manga url parsing success: 명탐정 코난 57권
MaruVolumeParser Manga url parsing success: 명탐정 코난 58권
MaruVolumeParser Manga url parsing success: 명탐정 코난 59권
MaruVolumeParser Manga url parsing success: 명탐정 코난 60권
MaruVolumeParser Manga url parsing success: 명탐정 코난 61권
MaruVolumeParser Manga url parsing success: 명탐정 코난 62권
MaruVolumeParser Manga url parsing success: 명탐정 코난 63권
MaruVolumeParser Manga url parsing success: 명탐정 코난 64권
MaruVolumeParser Manga url parsing success: 명탐정 코난 65권
MaruVolumeParser Manga url parsing success: 명탐정 코난 66권
MaruVolumeParser Manga url parsing success: 명탐정 코난 67권
MaruVolumeParser Manga url parsing success: 명탐정 코난 68권
MaruVolumeParser Manga url parsing success: 명탐정 코난 69권
MaruVolumeParser Manga url parsing success: 명탐정 코난 70권
MaruVolumeParser Manga url parsing success: 명탐정 코난 71권
MaruVolumeParser Manga url parsing success: 명탐정 코난 72권
MaruVolumeParser Manga url parsing success: 명탐정 코난 73권
MaruVolumeParser Manga url parsing success: 명탐정 코난 74권
MaruVolumeParser Manga url parsing success: 명탐정 코난 75권
MaruVolumeParser Manga url parsing success: 명탐정 코난 76권
MaruVolumeParser Manga url parsing success: 명탐정 코난 77권
MaruVolumeParser Manga url parsing success: 명탐정 코난 78권
MaruVolumeParser Manga url parsing success: 명탐정 코난 79권
MaruVolumeParser Manga url parsing success: 명탐정 코난 80권
MaruVolumeParser Manga url parsing success: 명탐정 코난 81권
MaruVolumeParser Manga url parsing success: 명탐정 코난 82권
MaruVolumeParser Manga url parsing success: 명탐정 코난 83권
MaruVolumeParser Manga url parsing success: 명탐정 코난 84권
MaruVolumeParser Manga url parsing success: 명탐정 코난 894~900화
MaruVolumeParser Manga url parsing success: 명탐정 코난 901~905화
MaruVolumeParser Manga url parsing success: 명탐정 코난 906~910화
MaruVolumeParser Manga url parsing success: 명탐정 코난 911~915화
MaruVolumeParser Manga url parsing success: 명탐정 코난 916~920화
MaruVolumeParser Manga url parsing success: 명탐정 코난 921화
MaruVolumeParser Manga url parsing success: 명탐정 코난 922화
MaruVolumeParser Manga url parsing success: 명탐정 코난 923화
MaruVolumeParser Manga url parsing success: 명탐정 코난 924화
MaruVolumeParser Manga url parsing success: 명탐정 코난 925화
MaruVolumeParser Manga url parsing success: 명탐정 코난 926화
MaruVolumeParser Manga url parsing success: 명탐정 코난 927화
MaruVolumeParser Manga url parsing success: 명탐정 코난 928화
MaruVolumeParser Manga url parsing success: 명탐정 코난 929화
MaruVolumeParser Manga url parsing success: 명탐정 코난 930화
MaruVolumeParser Manga url parsing success: 명탐정 코난 931화
MaruVolumeParser Manga url parsing success: 명탐정 코난 932화
MaruVolumeParser Manga url parsing success: 명탐정 코난 933화
MaruVolumeParser Manga url parsing success: 명탐정 코난 934화
MaruVolumeParser Manga url parsing success: 명탐정 코난 935화
MaruVolumeParser Manga url parsing success: 명탐정 코난 936화
MaruVolumeParser Manga url parsing success: 명탐정 코난 937화
MaruVolumeParser Manga url parsing success: 명탐정 코난 938화
MaruVolumeParser Manga url parsing success: 명탐정 코난 939화
MaruVolumeParser Manga url parsing success: 명탐정 코난 940화
MaruVolumeParser Manga url parsing success: 명탐정 코난 941화
MaruVolumeParser Manga url parsing success: 명탐정 코난 942화
MaruVolumeParser Manga url parsing success: 명탐정 코난 943화
MaruVolumeParser Manga url parsing success: 명탐정 코난 944화
MaruVolumeParser Manga url parsing success: 명탐정 코난 945화
MaruVolumeParser Manga url parsing success: 명탐정 코난 946화
MaruVolumeParser Manga url parsing success: 명탐정 코난 947화
MaruVolumeParser Manga url parsing success: 명탐정 코난 948화
MaruVolumeParser Manga url parsing success: 명탐정 코난 949화
MaruVolumeParser Manga url parsing success: 명탐정 코난 950화
MaruVolumeParser Manga url parsing success: 명탐정 코난 951화
MaruVolumeParser Manga url parsing success: 명탐정 코난 952화
MaruVolumeParser Manga url parsing success: 명탐정 코난 953화
MaruVolumeParser Manga url parsing success: 명탐정 코난 954화
MaruVolumeParser Manga url parsing success: 명탐정 코난 955화
MaruVolumeParser Manga url parsing success: 명탐정 코난 956화
MaruVolumeParser Manga url parsing success: 명탐정 코난 957화
MaruVolumeParser Manga url parsing success: 명탐정 코난 958화
MaruVolumeParser Manga url parsing success: 명탐정 코난 959화
MaruVolumeParser Manga url parsing success: 명탐정 코난 960화
MaruVolumeParser Manga url parsing success: 명탐정 코난 961화
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/archi
ves/1685343
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1685343'...
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/archi
ves/1695586
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
MaruMangaParser ParseMag - Parsing Manga request: http://www.yuncomics.com/archi
ves/1705230
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1705230'...
IVIagParser Try detour CloudProxy...
IVIagParser Try detour CloudProxy...
IVIagParser Try detour CloudProxy...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=3db90fbbcc08573313b01db62
767f36b;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1705230'...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=3db90fbbcc08573313b01db62
767f36b;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1695586'...
[RhinoEngine] Cookie: sucuri_cloudproxy_uuid_c12146289=3db90fbbcc08573313b01db62
767f36b;path=/;max-age=86400
MaruMangaParser Try to connect 'http://www.yuncomics.com/archives/1685343'...
MaruMangaParser Fail detour CloudProxy.
[2016-07-10 08:14:37][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fail
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

MaruMangaParser Fail detour CloudProxy.
[2016-07-10 08:14:37][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fail
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

MaruMangaParser Fail detour CloudProxy.
[2016-07-10 08:14:37][ERROR] [IVIagParser]org.iviagteam.magparser.exception.Fail
DetourException: Unknown cookie type
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
83)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
90)
        at org.iviagteam.magparser.MaruMangaParser.parsing(MaruMangaParser.java:
44)
        at org.iviagteam.magparser.MaruMangaParser.run(MaruMangaParser.java:36)

**Comment by HelloWorld017** [comment]
음 yuncomics -> blog.yuncomics로 가는 리다이렉션을 제대로 인지 못해서 생기는 문제인듯 하네요.

**Comment by HelloWorld017** [comment]
https://github.com/Team-IVIag/IVIag-Parser/commit/c12aa8a5ea0b42fe5216e91020204041a120205d
에서 수정했습니다.

**Comment by Dobob1022** [comment]
그러면 Iviag-Parser가 새로 릴리즈 될때까지 기다려야하나요?

**Comment by HelloWorld017** [comment]
오늘-내일 중으로 고친 버전 릴리즈하겠습니다.
