### ISSUE TITLE
만화가 다운이 안되는 경우가 생깁니다.

### ISSUE THREAD

**Issue by tommy0605** [Team-IVIag/IVIag-Viewer#13]
![i](https://cloud.githubusercontent.com/assets/21149549/17834680/48405088-6786-11e6-927a-ed0a32a360e4.JPG)
1~31화까지 받은 경우입니다.
중간에 비어있는 폴더는 안에 아무것도 없고 31화는 폴더생성도 안되었습니다.
여러번 다시 해보았지만 비어있는것만 다시 시도해보아도 안되더라구요...ㅠ
저에게만 있는 경우인지는 모르겠습니다 ㅠㅠ

**Comment by HelloWorld017** [comment]
신버전 사용에 체크하지 않으셨다면 다운안되는 폴더만 한번 체크해서 받아보세요.

**Comment by HelloWorld017** [comment]
수정했습니다. 잘 작동하는지 확인해주세요.
