### ISSUE TITLE
현재 마루마루 사이트

### ISSUE THREAD

**Issue by GODINGPIG** [Team-IVIag/IVIag-Viewer#18]
뷰어 사이트가 바뀌어서 2.5.4 버전으로 다운실행하면 
지정사이트가 바뀌서 실행이 안돼네요 아시고 계시겠지만 혹시나해서 적어봅니다 ^^

**Comment by HelloWorld017** [comment]
헉 와사비시럽 그거 뭔가 문제가 터질거 같다고 생각은 했는데 진짜로 문제가 있었군요!

**Comment by GODINGPIG** [comment]
항상 감사하고 응원하겠습니다!

**Comment by HelloWorld017** [comment]
버전 2.6에서 수정되었습니다.
