### ISSUE TITLE
실행오류

### ISSUE THREAD

**Issue by wodyd971** [Team-IVIag/IVIag-Viewer#4]
![1](https://cloud.githubusercontent.com/assets/17195074/14765612/ff429a86-0a23-11e6-9d55-9f881de6e232.PNG)

자바 새로받고 시작시켰는데 왜이러죳

**Comment by HelloWorld017** [comment]
https://github.com/Team-IVIag/IVIag-Viewer/releases/download/v2.2/IVIag-Viewer-v2.2-dist.jar
여기서 다운받으셔야 합니다.

**Comment by wodyd971** [comment]
![1](https://cloud.githubusercontent.com/assets/17195074/14765842/22b94d7e-0a2f-11e6-81f8-159206b7d5be.PNG)

여전한데요

**Comment by HelloWorld017** [comment]
세부정보를 보여주실 수 있으신가요

**Comment by wodyd971** [comment]
![1](https://cloud.githubusercontent.com/assets/17195074/14765895/bafd3102-0a31-11e6-9147-b1da240043bf.PNG)
![2](https://cloud.githubusercontent.com/assets/17195074/14765896/bb1e6ef8-0a31-11e6-8fb1-cafd988eb072.PNG)
![3](https://cloud.githubusercontent.com/assets/17195074/14765898/c7c2c5fa-0a31-11e6-9e3f-60219b001a7f.PNG)

명령으로 실행시키니 작동하네요
