### ISSUE TITLE
다운로드가 안됩니다

### ISSUE THREAD

**Issue by wodyd971** [Team-IVIag/IVIag-Viewer#5]
![01](https://cloud.githubusercontent.com/assets/17195074/15797847/728a1c6a-2a60-11e6-95e2-d3d678c8b062.PNG)
![02](https://cloud.githubusercontent.com/assets/17195074/15797848/7455ca26-2a60-11e6-89dc-3c90abbc8aad.PNG)
![03](https://cloud.githubusercontent.com/assets/17195074/15797849/75384f68-2a60-11e6-9923-3e53f9063487.PNG)
![04](https://cloud.githubusercontent.com/assets/17195074/15797850/75e8f688-2a60-11e6-9feb-74a83c13d127.PNG)
![05](https://cloud.githubusercontent.com/assets/17195074/15797851/7677b328-2a60-11e6-999a-17d557ccb904.PNG)
![06](https://cloud.githubusercontent.com/assets/17195074/15797852/784e1296-2a60-11e6-95f2-0e31c99264a9.PNG)
![07](https://cloud.githubusercontent.com/assets/17195074/15797853/7937445c-2a60-11e6-8c9b-3807aab43dbe.PNG)
![08](https://cloud.githubusercontent.com/assets/17195074/15797854/7a32eb0e-2a60-11e6-9e5f-e232c554614f.PNG)
![09](https://cloud.githubusercontent.com/assets/17195074/15797856/7bd09240-2a60-11e6-93c1-24efe2057408.PNG)
![10](https://cloud.githubusercontent.com/assets/17195074/15797862/89ef7634-2a60-11e6-9d1c-c5669b14e175.PNG)
![11](https://cloud.githubusercontent.com/assets/17195074/15797863/8b00ec88-2a60-11e6-9d49-08f4d6ba4b7a.PNG)
![12](https://cloud.githubusercontent.com/assets/17195074/15797864/8bb9d914-2a60-11e6-82a0-02061baa6d46.PNG)
![13](https://cloud.githubusercontent.com/assets/17195074/15797865/8c76b246-2a60-11e6-8671-f96a1fba685f.PNG)

해결 방법좀 알려주시겟습니까?

**Comment by HelloWorld017** [comment]
이미지 로딩방식이 바뀌었네요. 최대한 빠르게 수정하겠습니다.

**Comment by HelloWorld017** [comment]
[v2.4.1](https://github.com/Team-IVIag/IVIag-Viewer/releases/tag/v2.4.1) 에서 수정되었습니다
