### ISSUE TITLE
파일 다운로드시 에러가 납니다. 

### ISSUE THREAD

**Issue by Dobob1022** [Team-IVIag/IVIag-Viewer#8]
아마도 프로그래밍 하시다 메모리 할당을 작게 주신듯 하네요 크게주세용
오류는 
java.loang.OutOFMemoryError: Java heap space

오류가 뜨네요 !

**Comment by HelloWorld017** [comment]
java -jar에 옵션으로 메모리 할당이 가능합니다.
다음버전에서는 메모리 옵션을 포함한 sh와 bat파일을 같이 올리겠습니다

**Comment by Dobob1022** [comment]
음.. 자바쪽을 배우지 않아서;;; 혹시 명령어 자세히 알려주실수 있나요?

**Comment by HelloWorld017** [comment]
-Xms초기 힙사이즈
-Xmx최대 힙사이즈
입니다.
