### ISSUE TITLE
파일명

### ISSUE THREAD

**Issue by ogeho** [Team-IVIag/IVIag-Viewer#9]
파일명이 1,10,2,3 이런 식으로 밖에 인지할 수 있는 전자기기들이 많아서 담아서 볼경우 순서가 뒤엉킵니다. 다운로드시 파일명이 001, 002 이렇게 되도록 할 수 있나요?

**Comment by HelloWorld017** [comment]
옵션에 추가하겠습니다.

**Comment by ogeho** [comment]
네 감사합니다. 그리고 죄송하지만 폴더명도 001~ 로 시작하도록 해주셨음 합니다. 이미지 파일 뿐 아니라 폴더명도 뒤죽박죽인 숫자로 시작해서 섞이더군요.

**Comment by ogeho** [comment]
네 감사합니다. 그리고 죄송하지만 폴더명도 001~ 로 시작하도록 해주셨음 합니다. 이미지 파일 뿐 아니라 폴더명도 섞이더군요.

**Comment by HelloWorld017** [comment]
폴더명과 같은 경우 최대 자리수를 특정하기가 어려워서 힘들듯 합니다ㅠㅠ

**Comment by ogeho** [comment]
아 그렇군요. 컴퓨터 문외한이라.. 바로바로 잘 답변해주시고 적용도 해주셔서 감사합니다. 잘쓸게요!

**Comment by ogeho** [comment]
아 그렇군요. 컴퓨터 문외한이라.. 바로바로 잘 답변해주시고 적용도 해주셔서 감사합니다. 잘쓸게요!
